config/routes.rb
Rails.application.routes.draw do
  resources :interviews
  resources :diagnostics
  devise_for :users
  resource :user
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "diagnostics#index"
end

app/models/diagnostic.rb
class Diagnostic < ApplicationRecord
  belongs_to :user
  has_one :interview
  has_many_attached :photos
end

app/controllers/diagnostics_controller.rb
class DiagnosticsController < ApplicationController
  before_action :set_diagnostic, only: %i[ show edit update destroy ]

  # GET /diagnostics or /diagnostics.json
  def index
    @diagnostics = Diagnostic.all
  end

  # GET /diagnostics/1 or /diagnostics/1.json
  def show
  end

  # GET /diagnostics/new
  def new
    @diagnostic = Diagnostic.new
  end

  # GET /diagnostics/1/edit
  def edit
  end

  # POST /diagnostics or /diagnostics.json
  def create
    @diagnostic = Diagnostic.new(symptoms: params[:diagnostic][:symptom], user: current_user)
    @diagnostic.photos = params[:diagnostic][:photos] 
    respond_to do |format|
      if @diagnostic.save
        format.html { redirect_to new_interview_path(diagnostic:@diagnostic.id), notice: "Diagnostic was successfully created." }
        format.json { render :show, status: :created, location: @diagnostic }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @diagnostic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /diagnostics/1 or /diagnostics/1.json
  def update
    respond_to do |format|
      if @diagnostic.update(diagnostic_params)
        format.html { redirect_to diagnostic_url(@diagnostic), notice: "Diagnostic was successfully updated." }
        format.json { render :show, status: :ok, location: @diagnostic }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @diagnostic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diagnostics/1 or /diagnostics/1.json
  def destroy
    @diagnostic.destroy

    respond_to do |format|
      format.html { redirect_to diagnostics_url, notice: "Diagnostic was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_diagnostic
      @diagnostic = Diagnostic.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
end

app/helpers/diagnostics_helper.rb
module DiagnosticsHelper
end

app/views/diagnostics/_diagnostic.html.erb
<div id="<%= dom_id diagnostic %>">
  <div class="card text-center">
    <div class="card-header">
      Symptoms
    </div>
    <div class="card-body">
      <h5 class="card-title">This is the symptom you had</h5>
      <p class="card-text"><%= diagnostic.symptoms %></p>
      <div class="row mb-2">
        <% if diagnostic.photos.attached? %>
          <% diagnostic.photos.each do |photo| %>
            <div class="col-md-4">
              <div class="card mb-2">  
                <%= image_tag photo, size: '300x200' %>
              </div>
            </div>
          <% 
          end 
        end
        %>
      </div>
      <a href="#" class="btn btn-primary">Read more</a>
    </div>
  </div>
</div>

app/views/diagnostics/_form.html.erb
<%= form_with(model: diagnostic) do |form| %>
  <% if diagnostic.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(diagnostic.errors.count, "error") %> prohibited this diagnostic from being saved:</h2>
      <ul>
        <% diagnostic.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  

  <div>
    <%= form.label :symptoms, style: "display: block" %>
    <%= form.text_field :symptoms %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/diagnostics/edit.html.erb
<h1>Editing diagnostic</h1>

<%= render "form", diagnostic: @diagnostic %>

<br>

<div>
  <%= link_to "Show this diagnostic", @diagnostic %> |
  <%= link_to "Back to diagnostics", diagnostics_path %>
</div>

app/views/diagnostics/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container">
  <div class="row">
    <div class="col-sm">
      <div class="d-flex justify-content-center">      
        <h3>Diagnostics</h3>
      </div>
    </div>
    <div class="col-sm">
    </div>
    <div class="col-sm">
      <div class="d-flex justify-content-center">
        <%= link_to "New diagnostic", new_diagnostic_path, class: "btn btn-secondary btn-lg" %>
      </div>
    </div>
  </div>
</div>

<div id="diagnostikare" class="row mt-4">
  <% @diagnostics.each do |diagnostic| %>
  <div class="col-md-4 mb-4">
    <div class="card text-center">
      <div class="card-body">
        <h5 class="card-title">This is a description of the symptom</h5>
        <p class="card-text"><%= diagnostic.symptoms %></p>
        <%= link_to "Show this diagnostic", diagnostic, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
  <% end %>
  </div>
</div>


<%= javascript_tag do %>
  console.log('Pene')
<% end %>

app/views/diagnostics/new.html.erb
<h1>This is diagnostic</h1>

<!-- Name input -->
<%= form_with model:@diagnostic do |form| %>
<div class="form-outline mb-4 w-50">
    <%= form.label :symptom, "Here you can write your health problems" %>
    <%= form.text_area :symptom, class:'form-control' %>
    <%= form.file_field :photos, multiple: true %>
    <%= form.submit 'Create', class: "btn btn-primary mt-4" %>
</div>
<% end %>

<div>
  <%= link_to "Back to diagnostics", diagnostics_path %>
</div>

app/views/diagnostics/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @diagnostic %>

<div>
  <div class="d-flex justify-content-center">
    <%= link_to "Edit this diagnostic", edit_diagnostic_path(@diagnostic), class:"card-link" %> |
    <%= link_to "Back to diagnostics", diagnostics_path, class:"card-link" %>
  </div>
  <div class="d-flex justify-content-center mt-4">
    <%= button_to "Destroy this diagnostic", @diagnostic, method: :delete, class:"btn btn-secondary" %>
  </div>
</div>