config/routes.rb
Rails.application.routes.draw do
  resources :interviews
  resources :diagnostics
  devise_for :users
  resource :user
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "diagnostics#index"
end

app/controllers/interviews_controller.rb
class InterviewsController < ApplicationController
  before_action :set_interview, only: %i[ show edit update destroy ]

  # GET /interviews or /interviews.json
  def index
    @interviews = Interview.all
  end

  # GET /interviews/1 or /interviews/1.json
  def show
  end

  # GET /interviews/new
  def new
    @interview = Interview.new
    @doctores = Doctor.all
    @diagnostic = Diagnostic.find(params[:diagnostic])
  end

  # GET /interviews/1/edit
  def edit
  end

  # POST /interviews or /interviews.json
  def create
    @interview = Interview.new(interview_params)

    respond_to do |format|
      if @interview.save
        InterviewMailer.confirmed_interview(current_user.id,@interview.doctor.id ).deliver
        format.html { redirect_to interview_url(@interview), notice: "Interview was successfully created." }
        format.json { render :show, status: :created, location: @interview }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @interview.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /interviews/1 or /interviews/1.json
  def update
    respond_to do |format|
      if @interview.update(interview_params)
        format.html { redirect_to interview_url(@interview), notice: "Interview was successfully updated." }
        format.json { render :show, status: :ok, location: @interview }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @interview.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interviews/1 or /interviews/1.json
  def destroy
    @interview.destroy

    respond_to do |format|
      format.html { redirect_to interviews_url, notice: "Interview was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_interview
      @interview = Interview.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def interview_params
      params.require(:interview).permit(:doctor_id, :diagnostic_id)
    end
end

app/helpers/interviews_helper.rb
module InterviewsHelper
end

app/views/interviews/_form.html.erb
<%= form_with(model: interview) do |form| %>
  <% if interview.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(interview.errors.count, "error") %> prohibited this interview from being saved:</h2>

      <ul>
        <% interview.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row w-25 m-3">
    <select class="form-select" name="interview[doctor_id]">
      <% @doctores.each do |doctor| %>
        <option value="<%= doctor.id%>"><%= doctor.name %></option>
      <% end %>
    </select>
  </div>
  <div>
  <%= form.hidden_field :diagnostic_id, value: @diagnostic.id %>
  <div>
    <%= form.submit 'Create', class:'btn btn-primary' %>
  </div>
<% end %>

app/views/interviews/_interview.html.erb
<div id="<%= dom_id interview %>">
  <p>
    <strong>Doctor name:</strong>
    <%= interview.doctor_id%>
  </p>

  <p>
    <strong>Diagnostic:</strong>
    <%= interview.diagnostic_id %>
  </p>

</div>

app/views/interviews/edit.html.erb
<h1>Editing interview</h1>

<%= render "form", interview: @interview %>

<br>

<div>
  <%= link_to "Show this interview", @interview %> |
  <%= link_to "Back to interviews", interviews_path %>
</div>

app/views/interviews/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Interviews</h1>

<div id="interviews">
  <% @interviews.each do |interview| %>
    <%= render interview %>
    <p>
      <%= link_to "Show this interview", interview %>
    </p>
  <% end %>
</div>

<%= link_to "New interview", new_interview_path %>

app/views/interviews/new.html.erb
<h3>New interview</h3>

<p><b>This is the symptom that is going to tend: </b> <%= @diagnostic.symptoms %></p>

<%= render "form", interview: @interview %>
<br>

app/views/interviews/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="container text-center">
  <p><b>Symptoms:</b> <%= @interview.diagnostic.symptoms %></p>
  <p><b>Doctor:</b> <%= @interview.doctor.name %></p>

  <div class="mb-2">
    <%#= link_to "Back to interviews", interviews_path, class: 'btn btn-primary' %>
    <%= link_to "Destroy this interview", @interview, method: :delete, class: 'btn btn-danger' %>
  </div>
</div>